# Configuration file for VIRGO to consume related to this simulation configuration
 description: SIM_satellite visualization
 background_color: [0.0, 0.0, 0.05]
 highlight_color: [0.9, 0.9, 0.9]
 playback_speed: 1.0
 actors:
   earth: 
     mesh: PREFAB:earth
     scale: 1.0             # Size multiplier
     pos:   [0.0, 0.0, 0.0] # initial position in scene
     pyr:   [0.0, 0.0, 0.0] # initial pitch-yaw-roll rotation in scene
     pickable: 0
     driven_by: 0 # Not driven by any logged variable
   satellite:
     mesh: PREFAB:cube         # Size multiplier
     scale: 100.0
     pos: [0.0, 0.0, 0.0]       # initial position in scene
     pyr: [0.0, 0.0, 90.0]      # initial pitch-yaw-roll rotation in scene
     color: [0.6, 0.6, 0.6]
     pickable: 1
     driven_by:  # <group> <variable>
       pos: Satellite dyn.satellite.pos  # <dr group> <dr variable array of size 3>
       rot: Satellite dyn.satellite.R    # <dr group> <dr variable array of size 3x3>

 camera:
     follow: satellite